sudo: false
dist: trusty

git:
  depth: false

language: python

python:
  - 2.7
  - 3.5
  - 3.6

# Only deploy if master branch or like a release
install:
  pip install -r requirements.txt pytest pytest-cov pytest-pep8

script:
  - python -m pytest --cov=writers --pep8 writers tests

jobs:
  include:
    - stage: deploy
      if: branch = master OR branch =~ ^r[0-9]+.[0-9]+
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "$TRAVIS_REPO_SLUG" .
      - docker images
      - docker tag "$TRAVIS_REPO_SLUG" "$TRAVIS_REPO_SLUG":latest
      - if [[ "$TRAVIS_BRANCH" != "master" ]] ; then docker tag "$TRAVIS_REPO_SLUG" "$TRAVIS_REPO_SLUG":"${TRAVIS_BRANCH#r}" ; fi
      - docker push "$TRAVIS_REPO_SLUG"

after_success:
  - coveralls
