#FROM tensorflow/serving:1.10.1-gpu
#FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04
FROM ubuntu:18.04

# Dealing with a keyboard issue
COPY ./keyboard /etc/default/keyboard

RUN apt-get update && apt-get install -y \
    nvidia-cuda-toolkit \
    python3-pip

#RUN pip install enum34 futures mock six boto3 && \
#    pip install --pre 'protobuf>=3.0.0a3' && \
#    pip install -i https://testpypi.python.org/simple --pre grpcio

CMD bash
