name: Build & Push Docker Image

on:
  release:
    types: [published]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push ConfigWriter Image
      id: docker_build_writer
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.writer
        push: true
        tags: |
          ${{ github.repository }}-config-writer:latest
          ${{ github.repository }}-config-writer:${{ github.event.release.tag_name }}
    
    - name: ConfigWriter Image digest
      run: echo ${{ steps.docker_build_writer.outputs.digest }}

    - name: Build and push TensorFlow Serving Image
      id: docker_build_server
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.server
        push: true
        tags: |
          ${{ github.repository }}:latest
          ${{ github.repository }}:${{ github.event.release.tag_name }}
    
    - name: TensorFlow Serving Image digest
      run: echo ${{ steps.docker_build_server.outputs.digest }}
